-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.affectation
(
    id integer NOT NULL,
    classe_id integer,
    formateur_id integer,
    CONSTRAINT affectation_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.brief
(
    id serial NOT NULL,
    titre text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    duree integer NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    sprint_id integer NOT NULL,
    CONSTRAINT brief_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.classe
(
    id serial NOT NULL,
    nom text COLLATE pg_catalog."default" NOT NULL,
    annee_scolaire text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT classe_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.competence
(
    id serial NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    libelle text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT competence_pkey PRIMARY KEY (id),
    CONSTRAINT competence_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.competence_brief
(
    brief_id integer NOT NULL,
    competence_id integer NOT NULL,
    CONSTRAINT competence_brief_pkey PRIMARY KEY (brief_id, competence_id)
);

CREATE TABLE IF NOT EXISTS public.debriefing
(
    id serial NOT NULL,
    date date NOT NULL,
    commentaire text COLLATE pg_catalog."default",
    brief_id integer NOT NULL,
    CONSTRAINT debriefing_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.evaluation
(
    id serial NOT NULL,
    niveau text COLLATE pg_catalog."default" NOT NULL,
    etudiant_id integer NOT NULL,
    competence_id integer NOT NULL,
    debriefing_id integer NOT NULL,
    CONSTRAINT evaluation_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sprint
(
    id serial NOT NULL,
    nom text COLLATE pg_catalog."default" NOT NULL,
    duree integer NOT NULL,
    ordre_chronologique text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sprint_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    nom text COLLATE pg_catalog."default" NOT NULL,
    prenom text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    role role_enum NOT NULL,
    classe_id integer,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.affectation
    ADD CONSTRAINT fk_affectation_classe FOREIGN KEY (classe_id)
    REFERENCES public.classe (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.affectation
    ADD CONSTRAINT fk_affectation_formateur FOREIGN KEY (formateur_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.brief
    ADD CONSTRAINT fk_brief_sprint FOREIGN KEY (sprint_id)
    REFERENCES public.sprint (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.competence_brief
    ADD CONSTRAINT fk_cb_brief FOREIGN KEY (brief_id)
    REFERENCES public.brief (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.competence_brief
    ADD CONSTRAINT fk_cb_competence FOREIGN KEY (competence_id)
    REFERENCES public.competence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.debriefing
    ADD CONSTRAINT fk_debriefing_brief FOREIGN KEY (brief_id)
    REFERENCES public.brief (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.evaluation
    ADD CONSTRAINT fk_eval_competence FOREIGN KEY (competence_id)
    REFERENCES public.competence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.evaluation
    ADD CONSTRAINT fk_eval_debriefing FOREIGN KEY (debriefing_id)
    REFERENCES public.debriefing (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.evaluation
    ADD CONSTRAINT fk_eval_etudiant FOREIGN KEY (etudiant_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT fk_user_classe FOREIGN KEY (classe_id)
    REFERENCES public.classe (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

END;